### ISSUE TITLE
spuce install errors

### ISSUE THREAD

**Issue by fdkz** [audiofilter/homebrew-spuc#1]
I think there's a comma missing in spuce.rb

`system "cmake", "..", "-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5" *std_cmake_args`
should be
`system "cmake", "..", "-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5", *std_cmake_args`

At least without the comma, this happens:
```
fdkz@reggh:~$ brew install https://raw.githubusercontent.com/audiofilter/homebrew-spuc/master/spuce.rb
######################################################################## 100.0%
==> Downloading https://github.com/audiofilter/spuce/archive/0.4.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/spuce-0.4.1.tar.gz
Error: no implicit conversion of Array into Integer
Please report this bug:
    https://git.io/brew-troubleshooting
/Library/Caches/Homebrew/Formula/spuce.rb:12:in `*'
/Library/Caches/Homebrew/Formula/spuce.rb:12:in `block in install'
/usr/local/Library/Homebrew/extend/fileutils.rb:35:in `block in mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
/usr/local/Library/Homebrew/extend/fileutils.rb:34:in `mkdir'
/Library/Caches/Homebrew/Formula/spuce.rb:11:in `install'
/usr/local/Library/Homebrew/build.rb:130:in `block in install'
/usr/local/Library/Homebrew/formula.rb:919:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1532:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1523:in `stage'
/usr/local/Library/Homebrew/formula.rb:915:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'
fdkz@reggh:~$
```

**Comment by audiofilter** [comment]
Ok, thanks, will fix now
Tony

**Comment by audiofilter** [comment]
I fixed & checked, seems Ok

 brew reinstall spuce
==> Reinstalling spuce
==> Downloading https://github.com/audiofilter/spuce/archive/0.4.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/spuce-0.4.1.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/spuce/0.4.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRA
==> make install
🍺  /usr/local/Cellar/spuce/0.4.1: 68 files, 488K, built in 11 seconds
